version: "3"

services:
  nginx:
    # 재시작 정책
    # no: 어떤 상황에도 재시작하지 않음
    # always: 항상 재시작
    # unless-stopped: 명령어에 의해 중지되지 않는 한 항상 재시작
    # on-failure: on-failure 에러코드와 함께 컨테이너가 멈추면 재시작
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "3000:80"

  mysql:
    ## mysql 컨테이너가 정상작동하지 않는거같아 platform을 명시해줌
    platform: linux/x86_64
    build: ./mysql
    restart: unless-stopped
    container_name: app_mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: hugokang
      MYSQL_DATABASE: myapp

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
    depends_on:
      - mysql
      - nginx

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    depends_on:
      - mysql
      - nginx
      - backend
